<?php
const DATOS = ['Legionario'=>['tipo'=>'infanteria',
                              'civilizacion'=>'Romanos',
                              'costo'=>['alimento'=>50,
                                        'madera'=>0,
                                        'oro'=>20 ],
                              'estadistica'=>['puntosDeVida'=>75,
                                              'ataqueCuerpoACuarpo'=>12,
                                              'armaduraCuerpoACuerpo'=>2,
                                              'armaduraAntiPerforante'=>2,
                                              'velocidad'=>0.96,
                                              'lineaDeVision'=>7 ] 
                ],
                'Huscarle'=>['tipo'=>'infanteria',
                             'civilizacion'=>'Godos',
                             'costo'=>['alimento'=>52,
                                       'madera'=>0,
                                       'oro'=>26 ],
                             'estadistica'=>['puntosDeVida'=>60,
                                             'ataqueCuerpoACuarpo'=>10,
                                             'armaduraCuerpoACuerpo'=>0,
                                             'armaduraAntiPerforante'=>6,
                                             'velocidad'=>1.05,
                                             'lineaDeVision'=>3.5 ] 
                ],
                'Samurai'=>['tipo'=>'infanteria',
                            'civilizacion'=>'Japoneses',
                            'costo'=>['alimento'=>60,
                                      'madera'=>0,
                                      'oro'=>30 ],
                            'estadistica'=>['puntosDeVida'=>60,
                                            'ataqueCuerpoACuarpo'=>8,
                                            'armaduraCuerpoACuerpo'=>1,
                                            'armaduraAntiPerforante'=>1,
                                            'velocidad'=>1,
                                            'lineaDeVision'=>4 ] 
                ],
                'ArqueroDeTiroLargo'=>['tipo'=>'arquero',
                                       'civilizacion'=>'Britanos',
                                       'costo'=>['alimento'=>0,
                                                 'madera'=>35,
                                                 'oro'=>40 ],
                                        'estadistica'=>['puntosDeVida'=>35,
                                                        'ataqueCuerpoACuarpo'=>6,
                                                        'armaduraCuerpoACuerpo'=>0,
                                                        'armaduraAntiPerforante'=>0,
                                                        'velocidad'=>0.96,
                                                        'lineaDeVision'=>7 ]
                ],
                'ArqueroEmplumado'=>['tipo'=>'arquero',
                                     'civilizacion'=>'Maya',
                                     'costo'=>['alimento'=>0,
                                               'madera'=>45,
                                               'oro'=>45 ],
                                     'estadistica'=>['puntosDeVida'=>50,
                                                     'ataqueCuerpoACuarpo'=>5,
                                                     'armaduraCuerpoACuerpo'=>0,
                                                     'armaduraAntiPerforante'=>1.2,
                                                     'velocidad'=>1.20,
                                                     'lineaDeVision'=>6 ]
                ],
                'ArqueroDeRatan'=>['tipo'=>'arquero',
                                   'civilizacion'=>'Vietnamita',
                                   'costo'=>['alimento'=>0,
                                             'madera'=>50,
                                             'oro'=>45 ],
                                   'estadistica'=>['puntosDeVida'=>40,
                                                   'ataqueCuerpoACuarpo'=>6,
                                                   'armaduraCuerpoACuerpo'=>0,
                                                   'armaduraAntiPerforante'=>4,
                                                   'velocidad'=>1.10,
                                                   'lineaDeVision'=>6 ]
                ],
                'Catafracta'=>['tipo'=>'caballeria',
                               'civilizacion'=>'Bizantinos',
                               'costo'=>['alimento'=>70,
                                         'madera'=>0,
                                         'oro'=>75 ],
                                'estadistica'=>['puntosDeVida'=>110,
                                                'ataqueCuerpoACuarpo'=>9,
                                                'armaduraCuerpoACuerpo'=>2,
                                                'armaduraAntiPerforante'=>1,
                                                'velocidad'=>1.35,
                                                'lineaDeVision'=>4 ]
                ],
                'Centurion'=>['tipo'=>'caballeria',
                              'civilizacion'=>'Romanos',
                              'costo'=>['alimento'=>75,
                                        'madera'=>0,
                                        'oro'=>85 ],
                              'estadistica'=>['puntosDeVida'=>110,
                                              'ataqueCuerpoACuarpo'=>13,
                                              'armaduraCuerpoACuerpo'=>2,
                                              'armaduraAntiPerforante'=>3,
                                              'velocidad'=>1.35,
                                              'lineaDeVision'=>4 ]
                ],
                'Tarkano'=>['tipo'=>'caballeria',
                            'civilizacion'=>'Hunos',
                            'costo'=>['alimento'=>60,
                                      'madera'=>0,
                                      'oro'=>60 ],
                            'estadistica'=>['puntosDeVida'=>100,
                                            'ataqueCuerpoACuarpo'=>8,
                                            'armaduraCuerpoACuerpo'=>1,
                                            'armaduraAntiPerforante'=>3,
                                            'velocidad'=>1.40,
                                            'lineaDeVision'=>5 ]
                ],
                'Mangudai'=>['tipo'=>'caballeriaArquero',
                             'civilizacion'=>'Mongoles',
                             'costo'=>['alimento'=>0,
                                       'madera'=>55,
                                       'oro'=>65 ],
                             'estadistica'=>['puntosDeVida'=>60,
                                             'ataqueCuerpoACuarpo'=>6,
                                             'armaduraCuerpoACuerpo'=>0,
                                             'armaduraAntiPerforante'=>0,
                                             'velocidad'=>1.40,
                                             'lineaDeVision'=>6 ]
                ],
                'ArqueroACamello'=>['tipo'=>'caballeriaArquero',
                                    'civilizacion'=>'Bereberes',
                                    'costo'=>['alimento'=>0,
                                              'madera'=>50,
                                              'oro'=>60 ],
                                    'estadistica'=>['puntosDeVida'=>55,
                                                    'ataqueCuerpoACuarpo'=>7,
                                                    'armaduraCuerpoACuerpo'=>0,
                                                    'armaduraAntiPerforante'=>1,
                                                    'velocidad'=>1.40,
                                                    'lineaDeVision'=>5 ]
                ],
                'Ratha'=>['tipo'=>'caballeriaArquero',
                          'civilizacion'=>'Bengalies',
                          'costo'=>['alimento'=>0,
                                    'madera'=>60,
                                    'oro'=>60 ],
                          'estadistica'=>['puntosDeVida'=>100,
                                          'ataqueCuerpoACuarpo'=>10,
                                          'armaduraCuerpoACuerpo'=>3,
                                          'armaduraAntiPerforante'=>1,
                                          'velocidad'=>1.30,
                                          'lineaDeVision'=>6 ]
                ]
];
?>